/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hms;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author pmhussain
 */
public class MenuScreen extends javax.swing.JFrame {

    /**
     * Creates new form MenuScreen
     */
    public MenuScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPatient = new javax.swing.JMenuItem();
        nenuDoctors = new javax.swing.JMenuItem();
        menuServices = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel1.setText("Hospital Management Systems");

        jMenu1.setText("Main Menu");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuPatient.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuPatient.setText("Patients Information");
        menuPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatientActionPerformed(evt);
            }
        });
        jMenu1.add(menuPatient);

        nenuDoctors.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nenuDoctors.setText("Doctors Information");
        nenuDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nenuDoctorsActionPerformed(evt);
            }
        });
        jMenu1.add(nenuDoctors);

        menuServices.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuServices.setText("Services Information");
        menuServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuServicesActionPerformed(evt);
            }
        });
        jMenu1.add(menuServices);

        menuExit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        menuExit.setText("Exit ");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1046, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatientActionPerformed
        // Create Patient Class object and show it here
        Patients p = new Patients();
        p.setVisible(true);
        
        dispose();  // To close Menu Screen window
    }//GEN-LAST:event_menuPatientActionPerformed

    private void nenuDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nenuDoctorsActionPerformed
        // Create Doctors Class object and show it here
        Doctors  d = new Doctors();
        d.setVisible(true);
        
        dispose();  // To close Menu Screen window
    }//GEN-LAST:event_nenuDoctorsActionPerformed

    private void menuServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuServicesActionPerformed
        try {
            // Create Services Class object and show it here
            Services  s = new Services();
            s.setVisible(true);
            
            dispose();  // To close Menu Screen window
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(MenuScreen.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_menuServicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuPatient;
    private javax.swing.JMenuItem menuServices;
    private javax.swing.JMenuItem nenuDoctors;
    // End of variables declaration//GEN-END:variables
}
